### ISSUE TITLE
Consider removing dashes from package title

### ISSUE THREAD

**Issue by scowalt** [streamlink/streamlink-twitch-gui-chocolatey#1]
streamlink-twitch-gui => Streamlink Twitch GUI

**Comment by bastimeyer** [comment]
Do you mean the ID?
https://github.com/streamlink/streamlink-twitch-gui/blob/0e43c0fe2c2bb739e6c0fa4d535b18878f2ff9d0/build/resources/package/chocolatey/streamlink-twitch-gui.nuspec.tpl#L4

Would this require registering a new package?

**Comment by scowalt** [comment]
Nope, the title the line below.
https://github.com/streamlink/streamlink-twitch-gui/blob/0e43c0fe2c2bb739e6c0fa4d535b18878f2ff9d0/build/resources/package/chocolatey/streamlink-twitch-gui.nuspec.tpl#L5

**Comment by bastimeyer** [comment]
Ah, okay, the name tag has the value of package.name
https://github.com/streamlink/streamlink-twitch-gui/blob/0e43c0fe2c2bb739e6c0fa4d535b18878f2ff9d0/build/tasks/configs/template.js#L9

Sure, change it...
Just push all the changes that are necessary, you have push rights here
