### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by SAJewers** [streamlink/streamlink-twitch-gui-chocolatey#46]
https://github.com/streamlink/streamlink-twitch-gui/releases/tag/v2.0.0

**Comment by scowalt** [comment]
Thanks for opening this issue,

@Conjuro , did we have issues with newer versions of `streamlink-twitch-gui` due to using the installer? I vague recall something like that, but I've been OOTL for a bit

**Comment by lorthris** [comment]
+1 on this. With the old Twitch API dead we need 2.0 on Choco asap. ive had to switch from choco to manually installing using the .exe

**Comment by scowalt** [comment]
I have a draft up for this; https://community.chocolatey.org/packages/streamlink-twitch-gui/2.0.0

**Comment by scowalt** [comment]
v2.0.0 is shipped. LMK if there are any issues!

**Comment by bastimeyer** [comment]
Thanks
