### ISSUE TITLE
Current 2.0.0 release just installs 1.13.0 again

### ISSUE THREAD

**Issue by Starz0r** [streamlink/streamlink-twitch-gui-chocolatey#49]
Just a heads-up, it looks like the current Chocolatey release (2.0.0) just installs 1.13.0 again. This can be confirmed from looking at the package source from Chocolatey.

**Comment by scowalt** [comment]
Thanks! I saw this #48 , I'll correct it when I get the chance

**Comment by scowalt** [comment]
This should be resolved with the latest release, which is still pending moderation. Let me know if that's not the case! https://community.chocolatey.org/packages/streamlink-twitch-gui/2.0.0.220302
