### ISSUE TITLE
Version 2.3.0 on hold by chocolatey-ops

### ISSUE THREAD

**Issue by D3XX3R** [streamlink/streamlink-twitch-gui-chocolatey#56]
It seems like the automated validation has failed
https://community.chocolatey.org/packages/streamlink-twitch-gui/2.3.0

**Comment by scowalt** [comment]
Thanks, I'll look when I get the chance
<img width="739" alt="image" src="https://github.com/streamlink/streamlink-twitch-gui-chocolatey/assets/1100550/74b4150e-eccd-4638-85c9-b7318f16743c">

**Comment by scowalt** [comment]
I did a re-submit. package approved.
